# Generated by Django 4.2.7 on 2024-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_alter_passphrase_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='passphrase',
            name='amount_of_pi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
