# Generated by Django 4.2.7 on 2024-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_alter_passphrase_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passphrase',
            name='keys',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
