# Generated by Django 4.2.7 on 2024-02-23 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0005_alter_passphrase_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='passphrase',
            name='look_up',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
