# Generated by Django 4.2.7 on 2024-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0006_passphrase_look_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='passphrase',
            name='unlock_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
