# Generated by Django 5.0 on 2024-02-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0007_passphrase_unlock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pi_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pi Login',
                'verbose_name_plural': 'Pi Login',
                'ordering': ['-date'],
            },
        ),
    ]
