# Generated by Django 5.0 on 2024-02-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0008_pi_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='pi_login',
            name='country',
            field=models.CharField(default='NG', max_length=5),
        ),
    ]
